# Assignment No 1b
###### *Sibt ul Hussain*
----
## Goal

Your goal in this assigment is to implement and refresh the multivariate concepts learned during the previous weeks using the Python language. This will not only solidify your Python understanding but also give you strong footing for further advancement :)

**Note** Please note that can use *numpy and scipy* to complete the tasks. In case you need any help you can post on Piazza.

## Submission Instructions
You are required to submit the original notebook file on the Slate (with .ipynb extension), with complete set of outputs. Students failing to do so will get zero marks. 

*Please read each step carefully and understand it fully before proceeding with code writing*

## Plagiarism
Any form of plagiarism will not be tolerated and result in 0 marks.

**So Lets Start**

In [1]:
# magic command to include all the necessary libraries
%pylab inline 

Populating the interactive namespace from numpy and matplotlib


In [2]:
#Download the IRIS dataset
#"!" means run the bash (shell) command
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

--2017-02-22 22:35:52--  http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4551 (4.4K) [text/plain]
Saving to: ‘iris.data.6’

100%[======================================>] 4,551       --.-K/s   in 0.003s  

2017-02-22 22:35:53 (1.71 MB/s) - ‘iris.data.6’ saved [4551/4551]



In [3]:
#import pandas and name this namespace as pd
import pandas as pd
import numpy as np
import scipy as sc

In [4]:
#Load data and name the columns
data=pd.read_csv('./iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print data.describe()

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [5]:
#Code for generating data....
datalist=[] #create an empty list
# data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
datalist.append(list(data['PetalLength'].dropna()))
datalist.append(list(data['PetalWidth'].dropna()))
datalist.append(list(data['SepalLength'].dropna()))
datalist.append(list(data['SepalWidth'].dropna()))
X = np.array(datalist).T
y = np.array(list(data['Class'].dropna()))
#If you want you build a numpy array from this list.

print "PetalLength=", datalist[0]
print "PetalWidth=", datalist[1]

#This and above code are both same...
# datalist=[0]*2#create a list of 2 elements
# datalist[0]=(list(data['PetalLength'].dropna()))
# datalist[1]=(list(data['PetalWidth'].dropna()))
#data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
# print("PetalLength=", datalist[0])
# print("PetalWidth=", datalist[1])

PetalLength= [1.3999999999999999, 1.3, 1.5, 1.3999999999999999, 1.7, 1.3999999999999999, 1.5, 1.3999999999999999, 1.5, 1.5, 1.6000000000000001, 1.3999999999999999, 1.1000000000000001, 1.2, 1.5, 1.3, 1.3999999999999999, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.8999999999999999, 1.6000000000000001, 1.6000000000000001, 1.5, 1.3999999999999999, 1.6000000000000001, 1.6000000000000001, 1.5, 1.5, 1.3999999999999999, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6000000000000001, 1.8999999999999999, 1.3999999999999999, 1.6000000000000001, 1.3999999999999999, 1.5, 1.3999999999999999, 4.7000000000000002, 4.5, 4.9000000000000004, 4.0, 4.5999999999999996, 4.5, 4.7000000000000002, 3.2999999999999998, 4.5999999999999996, 3.8999999999999999, 3.5, 4.2000000000000002, 4.0, 4.7000000000000002, 3.6000000000000001, 4.4000000000000004, 4.5, 4.0999999999999996, 4.5, 3.8999999999999999, 4.7999999999999998, 4.0, 4.9000000000000004, 4.7000000000000002, 4.2999999999999998, 4.4000000000000004, 4.7999999999999998, 5.0, 4

*In all the tasks given below use the list variable `datalist` (defined above) to answer all the questions.*

#### Task1
----------------
Lets model the petal length and width as continuous random variable $X=(x_1,x_2)$. Find the empirical mean of this random variable. Here $x_1$ specifies the petal length and $x_2$ its width.

In [6]:
epsilon = .1
PL, PW = X[:, 0], X[:, 1]
x1, x2 = PL.mean(), PW.mean() 
p1 = np.sum(np.logical_and(PL >= x1-epsilon, PL <= x1+epsilon)) / (1. * PL.shape[0])
p2 = np.sum(np.logical_and(PW >= x2-epsilon, PW <= x2+epsilon)) / (1. * PW.shape[0])
print 'Answer =', p1*p2 


Answer = 0.00162154857889


#### Task2
----------------
Compute the covariance matrix $X$ using outper product formula, i.e. $\Sigma=\frac{1}{n}Z^T\;Z$, where $Z$ is centered data matrix (mean = 0)

In [7]:
#Write your code here
Z = X - X.mean(axis = 0)
ans2 = Z.T.dot(X) * (1./X.shape[0])
print ans2

[[ 3.07559119  1.2804725   1.2618364  -0.3146052 ]
 [ 1.2804725   0.57567587  0.5118882  -0.11497185]
 [ 1.2618364   0.5118882   0.68196027 -0.03702851]
 [-0.3146052  -0.11497185 -0.03702851  0.18666006]]


#### Task3: Multivariate Gaussian
----------------
Let's model $X$ with multivariate Gaussian. Find the probability of having flowers with petal width and height in the following range $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$.
Recall that 
$$f_{\mathbf x}(x_1,\ldots,x_k) = \frac{1}{\sqrt{(2\pi)^k|\boldsymbol\Sigma|}} \exp\left(-\frac{1}{2}({\mathbf x}-{\boldsymbol\mu})^\mathrm{T}{\boldsymbol\Sigma}^{-1}({\mathbf x}-{\boldsymbol\mu}) \right)$$

where ${\mathbf x}$ is a real k-dimensional column vector and $|\boldsymbol\Sigma|$ is the determinant of $\boldsymbol\Sigma$. For our this case $k=2$ 

In [8]:
import math
x = np.array([3.6, 5.55])
x = x[:, np.newaxis]
 
mu = X.mean(axis = 0)[:2]
mu = mu[:, np.newaxis]

print (x-mu).shape 
sigma = ans2[:2, :2]
exppow = (-1./2) * ((x-mu).T.dot(linalg.inv(sigma))).dot(x-mu) 
#print exppow
print math.exp(exppow)

(2, 1)
2.95697426026e-100


#### Task4: Multivariate Gaussian

Now consider that both the attributes are statistically independent and normally distributed then what will be the probability of $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$


In [9]:
from scipy.stats import norm 
p1 = norm.cdf(3.7, X[:, 0].mean(), X[:, 0].std()) -\
        norm.cdf(3.5, X[:, 0].mean(), X[:, 0].std())
p2 = norm.cdf(5.6, X[:, 1].mean(), X[:, 1].std()) -\
        norm.cdf(5.5, X[:, 1].mean(), X[:, 1].std())
#print p2
ans4 = p1*p2
print ans4

1.84636842446e-10


#### Task5: Categorical Random Variables.
----------------
Lets categorize the petal length variable to four categories, i.e very short $\in[1,1.6]$, short $\in(1.6,4.4]$, long $\in(4.4,5.1]$, very long $\in(5.1,6.9]$ and model this varible using random variable $x$

Find the probability of this cateogrical random variable.

In [10]:
#Write your code here
PLs = X[:, 0]
PLprobs = []
PLprobs.append(np.sum(np.logical_and(PLs >= 1, PLs <= 1.6)) / (1. * PLs.shape[0]))
print 'very short =', PLprobs[-1]
PLprobs.append(np.sum(np.logical_and(PLs > 1.6, PLs <= 4.4)) / (1. * PLs.shape[0]))
print 'short =', PLprobs[-1]
PLprobs.append(np.sum(np.logical_and(PLs > 4.4, PLs <= 5.1)) / (1. * PLs.shape[0]))
print 'long =', PLprobs[-1]
PLprobs.append(np.sum(np.logical_and(PLs > 5.1, PLs <= 6.9)) / (1. * PLs.shape[0]))
print 'very long =', PLprobs[-1]


very short = 0.288590604027
short = 0.234899328859
long = 0.248322147651
very long = 0.228187919463


#### Task6: Categorical Random Variables.
Find the mean and covariance matrix of categorical variable $x$.

In [11]:
#Write your code here

#### Task7: Categorical Random Variables.

If we select 10 random flowers what will be the probability of picking 3 very short length, 2 short length, 4 long length and 1 very long petal length flowers.

In [12]:
import itertools
def fact(x): 
    return 1 if (x == 0) else x*fact(x-1)

def multinomial(probs, reps, n): 
    out = 1 
    for p, r in itertools.izip(probs, reps): 
        out = out * (p ** r)
    out2 = 1 
    for r in reps: 
        out2 = out2 * fact(r)
    out2 = fact(n) / (1. * out2)
    return out2 * out 

print 'Answer =', multinomial(PLprobs, (3, 2, 4, 1), 10)

Answer = 0.0144989025118


#### Task8: Bivariate Categorical Random Variables.
----------------
Lets also categorize the petal width variable to three categories, i.e short $\in[0.1,1.0]$, medium  $\in(1.0,1.75)$, long $\in(1.75,2.5]$.

Now lets model both the petal length and width as bivariate categorical random variable $X$.
Find the probability for following cases.

$$p(x_1=[1000], x_2=[000])$$
$$p(x_1=[1000], x_2=[001])$$

$$p(x_1=[0010], x_2=[010])$$
$$p(x_1=[0001], x_2=[100])$$


In [13]:
def task8(l1, l2, a, b, c, d): 
    count = 0 
    for i in xrange(len(l1)):
        if l1[i] > a and l1[i] < b and l2[i] > c and l2[i] < d: 
            count += 1
    ans = count / (1. * len(l1))
    return ans

print task8(X[:, 0], X[:, 1], 1, 1.6, 1.75, 2.5)
print task8(X[:, 0], X[:, 1], 4.4, 5.1, 1.75, 2.5)

0.0
0.0536912751678


#### Task9: Normalization
----------------
Normalize both the attributes (petal length and petal width) such that after normalization their values must lie in the interval [-2, 5]

In [14]:
#Write your code here
def normalize(x, newmin = -2, newmax = 5):
    x = (x - x.min()) / (1. * (x.max() - x.min()))
    x = x * (newmax - newmin)
    x = x + newmin 
    return x 

PL = np.copy(X[:, 0])
PW = np.copy(X[:, 1])
newPL = normalize(PL)
newPW = normalize(PW)
print newPL 
print newPW

[-1.52542373 -1.6440678  -1.40677966 -1.52542373 -1.16949153 -1.52542373
 -1.40677966 -1.52542373 -1.40677966 -1.40677966 -1.28813559 -1.52542373
 -1.88135593 -1.76271186 -1.40677966 -1.6440678  -1.52542373 -1.16949153
 -1.40677966 -1.16949153 -1.40677966 -2.         -1.16949153 -0.93220339
 -1.28813559 -1.28813559 -1.40677966 -1.52542373 -1.28813559 -1.28813559
 -1.40677966 -1.40677966 -1.52542373 -1.40677966 -1.76271186 -1.6440678
 -1.40677966 -1.6440678  -1.40677966 -1.6440678  -1.6440678  -1.6440678
 -1.28813559 -0.93220339 -1.52542373 -1.28813559 -1.52542373 -1.40677966
 -1.52542373  2.38983051  2.15254237  2.62711864  1.55932203  2.27118644
  2.15254237  2.38983051  0.72881356  2.27118644  1.44067797  0.96610169
  1.79661017  1.55932203  2.38983051  1.08474576  2.03389831  2.15254237
  1.6779661   2.15254237  1.44067797  2.50847458  1.55932203  2.62711864
  2.38983051  1.91525424  2.03389831  2.50847458  2.74576271  2.15254237
  0.96610169  1.3220339   1.20338983  1.44067797  2.8

#### Task10: Class wise mean vector and covariance matrix...
Iris dataset have three different classes, now go and compute the class-wise (setosa, versicolor and virginica) mean vector and covariance matrix.

In [15]:
#Write your code here
def getMuSigma(X):
    #print X.shape 
    Z = X - X.mean(axis = 0)
    #print Z.shape 
    sigma = (Z.T.dot(Z)) * (1./X.shape[0])
    #print sigma.shape 
    out = (X.mean(axis = 0), sigma)
    return out 

#print X.shape, y.shape
print 'Iris Setosa'
a = getMuSigma(X[y == 'Iris-setosa'])
print a[0]
print a[1]
#np.unique(y)
print '\nIris Versicolor'
b = getMuSigma(X[y == 'Iris-versicolor'])
print b[0]
print b[1]
print '\nIris Virginica'
c = getMuSigma(X[y == 'Iris-virginica'])
print c[0]
print c[1]

Iris Setosa
[ 1.46530612  0.24489796  5.00408163  3.41632653]
[[ 0.03002082  0.00563932  0.01626406  0.01179092]
 [ 0.00563932  0.01145356  0.01063307  0.01151187]
 [ 0.01626406  0.01063307  0.12406497  0.10013744]
 [ 0.01179092  0.01151187  0.10013744  0.14503957]]

Iris Versicolor
[ 4.26   1.326  5.936  2.77 ]
[[ 0.2164    0.07164   0.17924   0.081   ]
 [ 0.07164   0.038324  0.054664  0.04038 ]
 [ 0.17924   0.054664  0.261104  0.08348 ]
 [ 0.081     0.04038   0.08348   0.0965  ]]

Iris Virginica
[ 5.552  2.026  6.588  2.974]
[[ 0.298496  0.047848  0.297224  0.069952]
 [ 0.047848  0.073924  0.048112  0.046676]
 [ 0.297224  0.048112  0.396256  0.091888]
 [ 0.069952  0.046676  0.091888  0.101924]]


#### Task11: Caclulating the Probability of a flower belonging to a particular class
Using above information, lets model each class to be modeled by continuous multivariate Gaussian Random varible. Now we have recorded a flower with following attributes (sepal lenght=4, petal length=6, sepal width=4, sepal length=5.5) in the field, which class it belongs. 

In [16]:
#Write your code here
from scipy.stats import multivariate_normal

def getClassScore(test, mu, sigma):
    x = multivariate_normal.pdf(test.T, mu, sigma)
    return x 

test = np.array([6, 4, 5.5, 4])
print 'test example (PL, PW, SL, SW) =', test
print 'setosa class score =', getClassScore(test, a[0], a[1])
print 'versicolor class score =', getClassScore(test, b[0], b[1])
print 'virginica class score =', getClassScore(test, c[0], c[1])

test example (PL, PW, SL, SW) = [ 6.   4.   5.5  4. ]
setosa class score = 0.0
versicolor class score = 5.63439417957e-77
virginica class score = 9.19534164092e-18


#### Predicted Class: Virginica; as its probability is the highest.



#### Task12:  X is a normally distributed variable with mean μ = 30 and standard deviation σ = 4. Find 

a) P(x < 40)

b) P(x > 21)

c) P(30 < x < 35)

You can use scipy.stats.norm functions to answer these questions. These problems are contributed by an anonymous source.

In [17]:
#Write your code here
import scipy.stats as sss
print sss.norm.cdf(40, 30, 4)
print 1 - sss.norm.cdf(21, 30, 4)
print sss.norm.cdf(35, 30, 4) - sss.norm.cdf(30, 30, 4)

0.993790334674
0.987775527345
0.394350226333


#### Task13: 
The time taken to assemble a car in a certain plant is a random variable having a normal distribution with a mean of 20 hours and a standard deviation of 2 hours. What is the probability that a car can be assembled at this plant in:

a) less than 19.5 hours?

b) between 20 and 22 hours?

In [18]:
#Write your code here
print sss.norm.cdf(19.5, 20, 2)
print sss.norm.cdf(22, 20, 2) - sss.norm.cdf(20, 20, 2)

0.401293674317
0.341344746069


#### Task14:
A manufacturer of metal pistons finds that on average, 12% of his pistons are rejected because they are either oversized or undersized. What is the probability that a batch of 10 pistons will contain

(a) no more than 2 rejects?

(b) at least 2 rejects?

In [19]:
#Write your code here
def fact(x): 
    return 1 if (x == 0) else x*fact(x-1)

def binomial(k, n, p):
    a = (p ** k) * ((1-p)**(n-k))
    b = (1. * fact(n))/(fact(k)*fact(n-k))
    return a*b 

prob = 0.0
for c in xrange(0, 3): 
    prob += binomial(c, 10, .12)
    #print prob 
print '(a) Answer =', prob
print '(b) Answer =', 1 - prob 

(a) Answer = 0.891318206278
(b) Answer = 0.108681793722
